### ISSUE TITLE
Supply CNCF with artwork

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#100]
## Status

- [x] Consensus on design (🎉  see https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-558670)
    - [x] Logo request #61 @schlomo
    - [x] Logo proposal GitHub discussion #63 @iboonox
        From https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-527026
        > here has only been enthusiastic and constructive/collaborative feedback so far. And everyone seems happy with the most recent iteration: https://github.com/gitops-working-group/gitops-working-group/discussions/63#discussioncomment-478223
    - [x] Announce request for consensus on mailing list @scottrigby
      [Sent email](https://lists.cncf.io/g/cncf-sig-app-delivery/message/244), comments open **until 5PM PT on March 31**
    - [x] Announce result of consensus on mailing list and Slack @scottrigby
- [x] Create CNCF artwork formats @iboonox
    see https://github.com/cncf/artwork for the required formats:
    > We prepare artwork in 2 formats (PNG & SVG), 3 layouts -- horizontal (also known as landscape format), stacked (which is closer to square), and icon (which does not include the name and is square), and at least 3 versions (color/black/white). So, that's at least 18 versions of most logos.
- [x] PR approved and merged #124
- [x] Open PRs in CNCF artwork repo @scottrigby 
    - [x] in review https://github.com/cncf/artwork/pull/233
    - [x] in review https://github.com/cncf/artwork/pull/234
- [x] Update provisional designs everywhere
    - [x] GitHub orgs (https://github.com/gitops-working-group and https://github.com/open-gitops)
    - [x] Twitter (https://twitter.com/OpenGitops and https://twitter.com/OpenGitops)
    - [x] Any material for GitOpsCon EU 2021. Example: the [CFP form header](https://docs.google.com/forms/d/e/1FAIpQLSeNahDbiEolx6WZmtxx4L65qmq7pZTX86nQAltq2uC12tCQYg/viewform). See #104 
- [x] Follow-up on this tweet https://twitter.com/GitOpsWG/status/1372688895146668036 @scottrigby done

Also see #97

**Comment by iboonox** [comment]
@scottrigby CNCF artwork fomats created https://github.com/gitops-working-group/gitops-working-group/pull/124
