### ISSUE TITLE
Set up WG communications team

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#108]
See https://github.com/gitops-working-group/gitops-working-group/issues/38

- [x] Create GitHub team @gitops-working-group/communications
- [x] Set up [Communications project board ](https://github.com/orgs/gitops-working-group/projects/4)
- [ ] Invite people to team
    - [x] YouTube @chris-short #135 
    - [x] YouTube owners current chairs #132 
    - [x] Twitter @soschwei #139
    - [x] Twitter etc @scottrigby #142
    - [x] Twitter etc @todaywasawesome #141
    - [ ] who else?

**Comment by scottrigby** [comment]
Related #135

**Comment by scottrigby** [comment]
Update OpenGitOps media team to match.
- Part of https://github.com/open-gitops/project/issues/2
